config/routes.rb
BloodDrive::Application.routes.draw do
  resources :drive_locations, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :drives, only: [:index] do
    member do
      get :confirmation
      get :notice
    end
    resources :drive_appointments, path: "appointments", only: [:new, :create]
  end
  resources :drive_appointments, path: "appointments", only: [:index]

  get "/auth/:provider/callback" => "sessions#create"
  get "/signin" => "sessions#new", :as => :signin
  get "/signout" => "sessions#destroy", :as => :signout
  get "/auth/failure" => "sessions#failure"

  root to: "drives#index"
end

app/models/drive_location.rb
class DriveLocation < ActiveRecord::Base
  belongs_to :drive


  def complete_address
    "#{address} #{address_extended} #{city}, #{state} #{zip}"
  end
end

app/controllers/drive_locations_controller.rb
class DriveLocationsController < ApplicationController
  def show
    @drive_location = DriveLocation.find(params[:id])
  end
end

app/views/drive_locations/_form.html.erb
<%= simple_form_for(@drive_location) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :address_extended %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :country %>
    <%= f.association :drive %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/drive_locations/edit.html.erb
<h1>Editing drive_location</h1>

<%= render 'form' %>

<%= link_to 'Show', @drive_location %> |
<%= link_to 'Back', drive_locations_path %>

app/views/drive_locations/index.html.erb
<h1>Listing drive_locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Address extended</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Country</th>
      <th>Drive</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @drive_locations.each do |drive_location| %>
      <tr>
        <td><%= drive_location.name %></td>
        <td><%= drive_location.address %></td>
        <td><%= drive_location.address_extended %></td>
        <td><%= drive_location.city %></td>
        <td><%= drive_location.state %></td>
        <td><%= drive_location.zip %></td>
        <td><%= drive_location.country %></td>
        <td><%= drive_location.drive %></td>
        <td><%= link_to 'Show', drive_location %></td>
        <td><%= link_to 'Edit', edit_drive_location_path(drive_location) %></td>
        <td><%= link_to 'Destroy', drive_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drive location', new_drive_location_path %>

app/views/drive_locations/new.html.erb
<h1>New drive_location</h1>

<%= render 'form' %>

<%= link_to 'Back', drive_locations_path %>

app/views/drive_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @drive_location.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @drive_location.address %>
</p>

<p>
  <strong>Address extended:</strong>
  <%= @drive_location.address_extended %>
</p>

<p>
  <strong>City:</strong>
  <%= @drive_location.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @drive_location.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @drive_location.zip %>
</p>

<p>
  <strong>Country:</strong>
  <%= @drive_location.country %>
</p>

<p>
  <strong>Drive:</strong>
  <%= @drive_location.drive %>
</p>

<%= link_to 'Edit', edit_drive_location_path(@drive_location) %> |
<%= link_to 'Back', drive_locations_path %>