config/routes.rb
BloodDrive::Application.routes.draw do
  resources :drive_locations, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :drives, only: [:index] do
    member do
      get :confirmation
      get :notice
    end
    resources :drive_appointments, path: "appointments", only: [:new, :create]
  end
  resources :drive_appointments, path: "appointments", only: [:index]

  get "/auth/:provider/callback" => "sessions#create"
  get "/signin" => "sessions#new", :as => :signin
  get "/signout" => "sessions#destroy", :as => :signout
  get "/auth/failure" => "sessions#failure"

  root to: "drives#index"
end

app/models/drive.rb
class Drive < ActiveRecord::Base
  has_many :drive_dates, dependent: :destroy
  has_many :drive_slots, -> { order("drive_slots.slot_at ASC") }, dependent: :destroy do
    def available
      t = DriveSlot.arel_table
      # Quick fix to close off a day
      where(t[:drive_appointments_count].lt(proxy_association.owner.total_appointments_available_per_slot).and(t[:slot_at].lt(DateTime.new(2014, 3, 22))))
    end

    def today
      t = DriveSlot.arel_table
      where(t[:slot_at].gteq(Date.today.beginning_of_day).and(t[:slot_at].lteq(Date.today.end_of_day)))
    end
  end
  has_many :drive_appointments, through: :drive_slots
  has_many :drive_locations, dependent: :destroy

  accepts_nested_attributes_for :drive_dates, allow_destroy: true
  accepts_nested_attributes_for :drive_locations, allow_destroy: true


  validates :recurs_every, presence: true

  after_create :generate_slots


  alias_attribute :to_s, :name


  def time_frame
    earliest_date = drive_dates.order(starts_at: :asc).first
    latest_date = drive_dates.order(ends_at: :desc).first
    "#{earliest_date.starts_at.to_s(:long_ordinal_date)} - #{latest_date.ends_at.to_s(:long_ordinal_date)}"
  end

  def total_appointments_available
    drive_slots.count * appointments_available_per_slot
  end

  def total_appointments_available_including_overflow
    drive_slots.count * total_appointments_available_per_slot
  end

  def total_appointments_available_per_slot
    appointments_available_per_slot + overflow_appointments_available_per_slot
  end

  def slots_filled
    drive_appointments.count
  end

  private

  def generate_slots
    drive_dates.each do |drive_date|
      current_slot = drive_date.starts_at
      until current_slot >= drive_date.ends_at
        drive_slots.where(DriveSlot.arel_table[:slot_at].eq(current_slot)).first_or_create
        current_slot += eval(recurs_every.gsub(' ', '.')) # MWAHAHAHAH!!!!!!
      end
    end
  end
end

app/controllers/drives_controller.rb
class DrivesController < ApplicationController
  before_action :set_drive, only: [:confirmation]

  def index
    @drives = Drive.all
  end

  def confirmation
  end


  private

  def set_drive
    @drive = Drive.find(params[:id])
  end
end

app/helpers/drives_helper.rb
module DrivesHelper
end

app/views/drives/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3 style="text-align: center;"><%= @drive %> Blood Drive</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <% if @drive_appointment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@drive_appointment.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% @drive_appointment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <%= simple_form_for [@drive, @drive_appointment], wrapper: :bootstrap3_horizontal, defaults: { right_column_html: { class: "col-sm-4" }, label_html: { class: "col-sm-offset-2 col-sm-2 control-label" }}, html: { class: "form-horizontal", style: "margin-top: 20px;", role: "form" } do |f| -%>
    <%= f.input :drive_slot_id, label: "Slot", as: :select, collection: @drive.drive_slots.available.map { |ds| [ds, ds.id] } %>
    <%= f.association :user do |u| -%>
      <%= u.input :name %>
      <%= u.input :email %>
      <%= u.input :phone %>
    <%- end -%>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6"><%= f.submit class: "btn btn-default pull-right" %></div>
    </div>
  <%- end -%>

  <div class="row">
    <div class="col-sm-12">
      <p class="subtext">We may send you follow up emails regarding your appointment</p>
    </div>
  </div>
</div>

app/views/drives/confirmation.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h3 style="text-align: center;"><%= @drive %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4 col-sm-offset-4 text-align: center;" style="margin-top: 20px;">
      <h4>Thank you for saving a life!</h4>
      You have been sent a confirmation email. Please contact <a href="mailto:donate112@icloud.com">donate112@icloud.com</a> if you have any questions.
    </div>
  </div>
</div>

app/views/drives/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Save a Life</h1>
    <p>Set an appointment to donate blood — <span class="underline"><span>You make a difference</span></span></p>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3" style="text-align: center;">
      <h2 style="text-align: center;">Blood Drives</h2>
      <%- @drives.each do |drive| -%>
        <div class="drive">
          <h3 style="margin-bottom: 0;"><%= link_to drive, new_drive_drive_appointment_path(drive) %></h3>
          <span class="dates"><%= drive.time_frame %></span>

          <%- drive.drive_locations.each do |drive_location| -%>
            <%= hidden_field_tag "drive_location_address-#{drive_location.id}", drive_location.complete_address, class: "drive-location-address", "data-drive-location-id" => drive_location.id %>

            <div class="location">
              <h5><%= drive_location.complete_address %></h5>
              <div id="drive_location-<%= drive_location.id %>" class="location-map"></div>
            </div>
          <%- end -%>

          <div class="col-sm-8 col-sm-offset-2"><p style="margin-top: 20px; text-align: left; font-weight: normal; font-size: 80%;"><%= drive.description.html_safe %></p></div>
        </div>
      <%- end -%>
    </div>
  </div>
</div>

app/views/drives/notice.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h3 style="text-align: center;"><%= @drive %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4 col-sm-offset-4 text-align: center;" style="margin-top: 20px;">
      <h4>You have already set an appointment for this blood drive.</h4>
      If you wish to change or cancel your appointment, please contact <a href="mailto:donate112@icloud.com">donate112@icloud.com</a>.
    </div>
  </div>
</div>