config/routes.rb
BloodDrive::Application.routes.draw do
  resources :drive_locations, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :drives, only: [:index] do
    member do
      get :confirmation
      get :notice
    end
    resources :drive_appointments, path: "appointments", only: [:new, :create]
  end
  resources :drive_appointments, path: "appointments", only: [:index]

  get "/auth/:provider/callback" => "sessions#create"
  get "/signin" => "sessions#new", :as => :signin
  get "/signout" => "sessions#destroy", :as => :signout
  get "/auth/failure" => "sessions#failure"

  root to: "drives#index"
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Blood Drives', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Appointments', drive_appointments_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'sign in via Facebook', signin_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blood Drive" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blood Drive" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyCkHr5qZaZx71w5Yv54z86mkoi59-R7z2I&sensor=true"></script>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <main role="main">
      <header>
        <%= render 'layouts/navigation' %>
      </header>

     <%= render 'layouts/messages' %>
     <%= yield %>
    </main>

    <footer>
      <div class="container">
        <div class="byline">brought to you by legacy program 112 — <span class="glyphicon glyphicon-heart" style="font-size: 10px;"></span> all heart <span class="glyphicon glyphicon-heart" style="font-size: 10px;"></span></div>
      </div>
    </footer>
  </body>
</html>